name: Package and Upload the source distribution to GCS

on:
  push:
    branches:
      - main
    paths:
      - 'model_trainer/**'

jobs:
  package-upload-to-gcs:
    name: Create Source dist and upload to gcs
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    # Install Build Tools
    - name: Install Build Tools
      run: |
        python -m pip install --upgrade pip setuptools wheel

    # Create a Source Distribution
    - name: Create Source Distribution
      run: |
        python model_trainer/setup.py sdist --format=gztar

    # Log in to GCP
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

    # Configure Google Cloud CLI
    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
    
    # UPload the dist to GCS
    - name: Upload to GCS
      run: |
        DIST_FILE=$(ls dist/*.tar.gz)
        gsutil cp $DIST_FILE gs://tymestack-artifacts/python-application/$(basename $DIST_FILE)
    
    # Trigger the CR Pipeline for New training
    - name: New Training & Deployment
      run: |
        gcloud run jobs execute crjob-test --region us-central1
    